import re
br_regexp=re.compile(r"Batman|Robin")
mo=br_regexp.search("Batman y Robin")
print(mo.group())
mo=br_regexp.search("Robin y Batman")
print(mo.group())
input()
mo=br_regexp.findall("Robin, Batman, Joker, robin, batman, Batman, Robin, BATMAN, ROBIN")
print(mo)
input()
